export type {
  Project,
  Service,
  TeamMember,
  Partner,
  Testimonial,
  BlogPost,
  ContactMessage,
  User,
  AuthResponse,
  CreateProjectDto,
  CreateServiceDto,
  CreateTeamMemberDto,
  CreatePartnerDto,
  CreateTestimonialDto,
  CreateBlogPostDto,
  CreateContactDto,
  LoginDto,
  RegisterDto,
} from '@/shared/types'
